### ISSUE TITLE
User Story: As a user of the app, I want to be able to navigate to the settings page so that I can see my settings options

### ISSUE THREAD

**Issue by PeterGottesman** [cse442-spring-2020-offering/cse442-semester-project-jackalopes#16]
Acceptance Tests:
1. Open the app. This brings you to the finder page
2. On the bottom of navigation bar, press on the settings tab
3. This should bring you to a page labeled settings with "Account Settings," "Discovery," "Usage," and "Notifications" headers.

**Comment by JudyMei** [comment]
Acceptance Test: Open app, Navigate to settings page, be able see options for account settings.
