### ISSUE TITLE
User Story: As a user wanting to change their profile, I want to be able to navigate to the Edit Profile page so that I can view my profile options 

### ISSUE THREAD

**Issue by PeterGottesman** [cse442-spring-2020-offering/cse442-semester-project-jackalopes#19]
Acceptance Tests:
1. Open up the app. This brings you to the Finder Page
2. On the navigation bar on the bottom of the screen, press the "Edit Profile" page
3. This should bring you to a page labeled "Edit Profile" at the top.

**Comment by JessicaGrogan** [comment]
Acceptance test:
In terminal: run npm start
-scan the QR code
When the app is loaded:
-Press the Edit profile tab
-See that this page loads and has the options of the edit settings page as we discussed
