### ISSUE TITLE
Create a login page in app that connects to API

### ISSUE THREAD

**Issue by TristanWiley** [cse442-spring-2020-offering/cse442-semester-project-jackalopes#33]
Task Tests: 
1. Open app
2. Upon opening the app, you should arrive at the login screen
3. Enter user account into fields, press login button, if you are redirected to the swiping page, success!

**Comment by JudyMei** [comment]
Error: There is a bug that when you press Enter with the Keyboard in view, it gives an error. However, when you press enter with the Keyboard minimizes page works as expected.
