### ISSUE TITLE
Implement edit user profile dialogs

### ISSUE THREAD

**Issue by PeterGottesman** [cse442-spring-2020-offering/cse442-semester-project-jackalopes#44]
Task Test:
1. Run the app
2. Navigate to Edit Profile page
3. Try to edit whether or not you are animal friendly
4. Input dialog should pop up
5. Choose whether or not you are pet friendly
6. You should see a message in response to your respective choice
7. Press close
done

**Comment by JessicaGrogan** [comment]
Task Test:
1. Run the app
2. Navigate to Edit Profile page
3. Slide the slider to set a distance and see the distance show with the slider.
